version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - README.md

max_jobs: 1

image: Visual Studio 2017

clone_folder: c:\projects\gibbed-yakuza0

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - git submodule update --init --recursive

configuration:
  - Debug

build:
  project: Yakuza 0.sln
  parallel: true
  verbosity: minimal

before_build:
  - nuget restore

after_build:
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!bin/Test.exe -x!*/LICENSE.txt y0-%APPVEYOR_BUILD_VERSION%.zip ./LICENSE.txt ./README.txt git-log.txt bin/*.exe bin/*.dll
  - 7z a -r -tzip -mx=9 -x!bin/Test.exe -x!*/LICENSE.txt y0-%APPVEYOR_BUILD_VERSION%-with-symbols.zip ./LICENSE.txt ./README.txt git-log.txt bin/*.exe bin/*.dll bin/*.pdb

artifacts:
  - path: '*-*.zip'
